# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.cache/wt [current_project]
set_property parent.project_path D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/imports/Desktop/memfile2.dat
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/imports/Desktop/memfile.dat
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/imports/Desktop/memfile1.dat
}
read_verilog -library xil_defaultlib -sv {
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/IO.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/adder.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/alu.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/aludec.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/controller.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/imports/Desktop/dMemoryDecoder.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/datapath.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/dmem.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/flopr.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/imem.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/maindec.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/mips.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/mux2.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/mux7seg.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/regfile.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/s12.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/signext.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/unsignext.sv
  D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/sources_1/new/Top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/constrs_1/imports/Downloads/Nexys4DDR.xdc
set_property used_in_implementation false [get_files D:/Subjects/计算机组成与体系结构/实验项目/实验一_单周期MIPS处理器/SingleCycleProcessor/SingleCycleProcessor.srcs/constrs_1/imports/Downloads/Nexys4DDR.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
